// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AesDecrypt(arg1, arg2) {
  return window['go']['main']['App']['AesDecrypt'](arg1, arg2);
}

export function AesEncrypt(arg1, arg2) {
  return window['go']['main']['App']['AesEncrypt'](arg1, arg2);
}

export function Base64Decode(arg1) {
  return window['go']['main']['App']['Base64Decode'](arg1);
}

export function Base64Encode(arg1) {
  return window['go']['main']['App']['Base64Encode'](arg1);
}

export function CreateMd5Hash(arg1) {
  return window['go']['main']['App']['CreateMd5Hash'](arg1);
}

export function GpgAddKey(arg1, arg2) {
  return window['go']['main']['App']['GpgAddKey'](arg1, arg2);
}

export function GpgDeleteKey(arg1) {
  return window['go']['main']['App']['GpgDeleteKey'](arg1);
}

export function GpgListKeys() {
  return window['go']['main']['App']['GpgListKeys']();
}

export function JwtDecode(arg1) {
  return window['go']['main']['App']['JwtDecode'](arg1);
}

export function JwtEncode(arg1, arg2) {
  return window['go']['main']['App']['JwtEncode'](arg1, arg2);
}
