// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hash} from '../models';

export function CreateMd5Hash(arg1:string):Promise<hash.HashResult>;
