// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {crypto} from '../models';
import {hash} from '../models';

export function AesDecrypt(arg1:string,arg2:string):Promise<crypto.CryptoDecryptResult>;

export function AesEncrypt(arg1:string,arg2:string):Promise<crypto.CryptoEncryptResult>;

export function CreateMd5Hash(arg1:string):Promise<hash.HashResult>;
