// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AesDecrypt(arg1, arg2) {
  return window['go']['main']['App']['AesDecrypt'](arg1, arg2);
}

export function AesEncrypt(arg1, arg2) {
  return window['go']['main']['App']['AesEncrypt'](arg1, arg2);
}

export function CreateMd5Hash(arg1) {
  return window['go']['main']['App']['CreateMd5Hash'](arg1);
}
