name: changelog-release

on:
  push:
    tags:
      - '*'
jobs:
  changelog:
    name: changelog
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        id: checkout
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit changes
        id: commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push https://${{ secrets.GIT_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git HEAD:master

      - name: Create Release
        uses: ncipollo/release-action@v1
        id: release
        with:
          body: ${{ steps.git-cliff.outputs.content }}
          token: ${{ secrets.GIT_TOKEN }}